### ISSUE TITLE
Definir a base conceitual do jogo

### ISSUE THREAD

**Issue by radunzz** [four-landia/Lost-princesses#2]
- [x]  Referências: literatura, mídias em geral e outros jogos
- [x]  Roteiro: início, meio e fim
- [x]  Personagens: perfis, evolução
- [x]  Artefatos: armas, poções etc.
- [x]  Mundo/universo

**Comment by Fevrosa** [comment]
Vamos utilizar como referência jogos de labirinto e princesas da Disney .

**Comment by Fevrosa** [comment]
O universo dos dois jogos estão integrados. De um lado a princesa tentando chegar ao
castelo e do outro a madrasta/bruxa tentando impedir.
A princesa tem que pegar a "chave", que para cada princesa será um objeto/pessoa
As princesas que escolhemos são:

Referências:
Labirinto
Disney
Efeito zoom
Labirinto circular
Piskel App

Roteiro: 
As princesas começam no início do labirinto e tem como objetivo chegar no castelo. Para que consigam entrar no castelo, cada princesa precisa de uma “chave” que está localizada através do percurso no labirinto. O segundo player é a madrasta/bruxa que tem como objetivo impedir a chegada da princesa ao castelo. 

Personagens: 
Cinderela, Rapunzel, Branca de neve e Madrasta/bruxa.

Artefatos: 
Cinderela > Chave: Sapatinho (chave para abrir o castelo)
> Poder: Fada madrinha (move a princesa para outro local, facilitando sua chegada ao castelo)

Rapunzel > Chave: Camaleão (pascal)
> Poder: Camuflagem ou frigideira (se escondendo ou se defendendo da madrasta/bruxa)

Branca de neve > Chave: Anões
> Poder: Ajuda dos animais (move a princesa para outro local, facilitando seu caminho para a chegada ao castelo)

Madrasta/bruxa > Poder: Rastrear os passos da princesa por X tempo.
> Poder 2: bússola (determina o caminho onde a princesa se encontra, facilitando a caçada da bruxa)


Mundo/universo:
Floresta magica. 
Castelo (disney)

Obstáculos: (caso de tempo)
No lugar de colocar diretamente o item “chave”, colocar dois baús no labirinto, um com a chave e outro com um item que faz com que a personagem “morra” e volte para o início do labirinto.

Baú do mal:
-Branca de neve: maçã
-Rapunzel: tesoura
-Cinderela: relógio
